# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: action
    displayName: choose import or export
    type: string
    values:
      - import
      - export

  - name: base
    displayName: "Airtable base code"
    type: string
    values:
      - JP
      - TW
      - KR
      - HK
      - VAULT

  - name: blob
    displayName: 'Blob name (optional, default is: airtable-[base_code]-[yyyyMMddhhmm].zip)'
    type: string
    default: ''

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    python3 test.py
  displayName: 'Run a python script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    sh test.sh
  env:
    TAG: "testing"
    BASE: "$(base)"
    BLOB: "$(blob)"
  displayName: 'Run a shell script'